version: "3"

services:
  app:
    container_name: app
    build:
      context: ""
      dockerfile: ./docker/Dockerfile
    image: springboot
    volumes:
      - ./urlshortner:/urlshortner
    ports:
      - "8080:8080"
    networks:
      - spring_net
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - spring_net
    volumes:
      - ./urlshortner:/urlshortner

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - spring_net
    volumes:
      - ./urlshortner:/urlshortner
networks:
  spring_net:
    driver: bridge